import json
import os
import sys

# Script to build full 112+ algorithm knowledge base into src/algorithm_knowledge_base.py and .json

PRIMARY_CATEGORIES = [
    "Searching",
    "Sorting",
    "Classification",
    "Regression",
    "Graph Algorithms",
    "Tree Algorithms",
    "Dynamic Programming",
    "Greedy Algorithms",
    "Backtracking",
    "Machine Learning / AI"
]

REQUIRED_FIELDS = [
    "id", "name", "category", "description", "problem_patterns",
    "data_structures", "requirements", "input_characteristics",
    "constraints", "best_use_cases", "time_complexity", "space_complexity",
    "advantages", "limitations", "alternatives", "python_template"
]

kb = []

# ==================== 1. SEARCHING ====================
kb.extend([
    {
        "id": "binary_search",
        "name": "Binary Search",
        "category": "Searching",
        "description": "Efficient search algorithm that finds the position of a target value within a sorted array by repeatedly dividing the search interval in half.",
        "problem_patterns": ["sorted array lookup", "find element in sorted list", "search in logarithmic time", "half search space", "find square root or threshold", "sorted data existence check"],
        "data_structures": ["Array", "Sorted List"],
        "requirements": ["Input array must be pre-sorted in ascending/descending order", "Random access by index O(1)"],
        "input_characteristics": ["Sorted numerical or string sequence", "Known boundaries"],
        "constraints": ["Data structure must support fast indexed access", "Requires prior sorting step"],
        "best_use_cases": ["Searching in large sorted numerical arrays", "Finding boundaries/thresholds in monotonic functions", "Range lookup operations"],
        "time_complexity": "O(log n)",
        "space_complexity": "O(1)",
        "advantages": ["Very fast for large sorted lists", "Minimal memory overhead"],
        "limitations": ["Requires data to be pre-sorted", "Not suitable for linked lists"],
        "alternatives": ["Interpolation Search", "Hash Table Lookup", "Exponential Search"],
        "python_template": "def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1"
    },
    {
        "id": "linear_search",
        "name": "Linear Search",
        "category": "Searching",
        "description": "Sequential search algorithm that checks every element in a list one by one until a match is found or the end is reached.",
        "problem_patterns": ["unsorted list search", "find first occurrence", "small dataset lookup", "sequential search", "find match in unsorted array"],
        "data_structures": ["Array", "Linked List", "Iterable"],
        "requirements": ["None (works on unsorted or arbitrary data)"],
        "input_characteristics": ["Unsorted or arbitrary order", "Small to medium size"],
        "constraints": ["Inefficient for large arrays"],
        "best_use_cases": ["Small collections", "Unsorted list single-pass lookup", "When sorting cost exceeds search cost"],
        "time_complexity": "O(n)",
        "space_complexity": "O(1)",
        "advantages": ["Simple to implement", "No prerequisite sorting or index required"],
        "limitations": ["Linear time lookup O(n) becomes slow for big datasets"],
        "alternatives": ["Binary Search", "Hash Table Lookup"],
        "python_template": "def linear_search(arr, target):\n    for idx, val in enumerate(arr):\n        if val == target:\n            return idx\n    return -1"
    },
    {
        "id": "hash_table_lookup",
        "name": "Hash Table / Dictionary Lookup",
        "category": "Searching",
        "description": "Data structure technique that stores key-value pairs using a hash function for near-constant time lookups and insertions.",
        "problem_patterns": ["constant time lookup", "frequency count", "find duplicates", "two sum problem", "key value mapping", "fast index matching"],
        "data_structures": ["Hash Map", "Hash Set", "Dictionary"],
        "requirements": ["Keys must be hashable and immutable"],
        "input_characteristics": ["Unique keys or items", "Unordered data"],
        "constraints": ["Consumes extra memory for hash storage", "Potential hash collisions"],
        "best_use_cases": ["Repeated fast lookups", "Element frequency counting", "Caching and memoization"],
        "time_complexity": "O(1) average, O(n) worst case",
        "space_complexity": "O(n)",
        "advantages": ["Constant time average lookup O(1)", "Versatile key-value associations"],
        "limitations": ["Unordered data storage", "Memory overhead"],
        "alternatives": ["Binary Search Tree", "Trie"],
        "python_template": "def hash_lookup(arr, target):\n    lookup_map = {val: idx for idx, val in enumerate(arr)}\n    return lookup_map.get(target, -1)"
    },
    {
        "id": "jump_search",
        "name": "Jump Search",
        "category": "Searching",
        "description": "Searching algorithm for sorted arrays that checks fewer elements than linear search by jumping ahead by fixed steps.",
        "problem_patterns": ["jump ahead search", "block search in sorted array", "sub-linear search without binary split"],
        "data_structures": ["Array", "Sorted List"],
        "requirements": ["Input array must be sorted"],
        "input_characteristics": ["Sorted list", "Random access indexing"],
        "constraints": ["Optimal step size is sqrt(n)"],
        "best_use_cases": ["Searching sorted arrays when jumping backwards is expensive"],
        "time_complexity": "O(sqrt(n))",
        "space_complexity": "O(1)",
        "advantages": ["Better than linear search", "Only jumps backward once"],
        "limitations": ["Slower than binary search O(log n)"],
        "alternatives": ["Binary Search", "Exponential Search"],
        "python_template": "import math\ndef jump_search(arr, target):\n    n = len(arr)\n    step = int(math.sqrt(n))\n    prev = 0\n    while arr[min(step, n)-1] < target:\n        prev = step\n        step += int(math.sqrt(n))\n        if prev >= n: return -1\n    while arr[prev] < target:\n        prev += 1\n        if prev == min(step, n): return -1\n    if arr[prev] == target: return prev\n    return -1"
    },
    {
        "id": "interpolation_search",
        "name": "Interpolation Search",
        "category": "Searching",
        "description": "Improved binary search variant for uniformly distributed sorted arrays that estimates position based on target value relative to low/high values.",
        "problem_patterns": ["uniformly distributed sorted search", "phonebook style search", "numeric range interpolation"],
        "data_structures": ["Array", "Sorted List"],
        "requirements": ["Data must be sorted and uniformly distributed"],
        "input_characteristics": ["Sorted numbers with uniform intervals"],
        "constraints": ["Performance degrades to O(n) if data is non-uniform"],
        "best_use_cases": ["Searching in large uniformly distributed numerical sorted data"],
        "time_complexity": "O(log log n) average, O(n) worst case",
        "space_complexity": "O(1)",
        "advantages": ["Sub-logarithmic search O(log log n) on uniform data"],
        "limitations": ["Sensitive to non-uniform distribution"],
        "alternatives": ["Binary Search", "Exponential Search"],
        "python_template": "def interpolation_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high and target >= arr[low] and target <= arr[high]:\n        if low == high:\n            if arr[low] == target: return low\n            return -1\n        pos = low + int(((high - low) / (arr[high] - arr[low])) * (target - arr[low]))\n        if arr[pos] == target: return pos\n        if arr[pos] < target: low = pos + 1\n        else: high = pos - 1\n    return -1"
    },
    {
        "id": "exponential_search",
        "name": "Exponential Search",
        "category": "Searching",
        "description": "Search algorithm for unbounded or infinite sorted lists that finds a range where target resides by doubling indices, then performs binary search.",
        "problem_patterns": ["unbounded array search", "infinite stream search", "unknown length sorted list"],
        "data_structures": ["Array", "Sorted Stream"],
        "requirements": ["Input data must be sorted"],
        "input_characteristics": ["Sorted array or unbounded stream"],
        "constraints": ["Requires random access by index"],
        "best_use_cases": ["Searching in unbounded / infinite sorted arrays", "Target is near the beginning of list"],
        "time_complexity": "O(log n)",
        "space_complexity": "O(1)",
        "advantages": ["Works on infinite/unbounded lists", "Fast when target is near start"],
        "limitations": ["Requires pre-sorted data"],
        "alternatives": ["Binary Search", "Jump Search"],
        "python_template": "def exponential_search(arr, target):\n    if len(arr) == 0: return -1\n    if arr[0] == target: return 0\n    i = 1\n    while i < len(arr) and arr[i] <= target:\n        i = i * 2\n    left = i // 2\n    right = min(i, len(arr) - 1)\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: left = mid + 1\n        else: right = mid - 1\n    return -1"
    },
    {
        "id": "fibonacci_search",
        "name": "Fibonacci Search",
        "category": "Searching",
        "description": "Comparison-based search technique for sorted arrays using Fibonacci numbers to divide the array.",
        "problem_patterns": ["fibonacci split search", "addition only search", "sorted array search without division"],
        "data_structures": ["Array", "Sorted List"],
        "requirements": ["Sorted input array"],
        "input_characteristics": ["Sorted numeric array"],
        "constraints": ["Requires generating Fibonacci numbers"],
        "best_use_cases": ["Systems where multiplication or division is computationally expensive"],
        "time_complexity": "O(log n)",
        "space_complexity": "O(1)",
        "advantages": ["Uses only addition and subtraction, no division"],
        "limitations": ["Slightly more complex than binary search"],
        "alternatives": ["Binary Search", "Jump Search"],
        "python_template": "def fibonacci_search(arr, target):\n    fibM2, fibM1 = 0, 1\n    fibM = fibM2 + fibM1\n    n = len(arr)\n    while (fibM < n):\n        fibM2, fibM1 = fibM1, fibM\n        fibM = fibM2 + fibM1\n    offset = -1\n    while (fibM > 1):\n        i = min(offset + fibM2, n - 1)\n        if (arr[i] < target):\n            fibM, fibM1 = fibM1, fibM2\n            fibM2 = fibM - fibM1\n            offset = i\n        elif (arr[i] > target):\n            fibM = fibM2\n            fibM1 = fibM1 - fibM2\n            fibM2 = fibM - fibM1\n        else: return i\n    if(fibM1 and offset + 1 < n and arr[offset + 1] == target): return offset + 1\n    return -1"
    },
    {
        "id": "ternary_search",
        "name": "Ternary Search",
        "category": "Searching",
        "description": "Divide-and-conquer search algorithm that divides the array into three equal parts to find a target value or unimodal function peak.",
        "problem_patterns": ["unimodal function maximum/minimum", "three way split search", "peak finding"],
        "data_structures": ["Array", "Monotonic / Unimodal Function"],
        "requirements": ["Input must be sorted or unimodal"],
        "input_characteristics": ["Continuous or discrete unimodal values"],
        "constraints": ["More comparisons per step than binary search"],
        "best_use_cases": ["Finding maximum or minimum of a unimodal function"],
        "time_complexity": "O(log3 n)",
        "space_complexity": "O(1)",
        "advantages": ["Effective for continuous optimization/peak finding"],
        "limitations": ["Makes more comparisons than binary search for discrete array search"],
        "alternatives": ["Binary Search", "Golden Section Search"],
        "python_template": "def ternary_search(arr, target, l, r):\n    if r >= l:\n        mid1 = l + (r - l) // 3\n        mid2 = r - (r - l) // 3\n        if arr[mid1] == target: return mid1\n        if arr[mid2] == target: return mid2\n        if target < arr[mid1]: return ternary_search(arr, target, l, mid1 - 1)\n        elif target > arr[mid2]: return ternary_search(arr, target, mid2 + 1, r)\n        else: return ternary_search(arr, target, mid1 + 1, mid2 - 1)\n    return -1"
    },
    {
        "id": "bfs_grid_search",
        "name": "BFS Search (Grid / Tree / Graph)",
        "category": "Searching",
        "description": "Explores nodes level by level using a queue to find target element or shortest unweighted path.",
        "problem_patterns": ["level order search", "shortest path unweighted grid", "nearest neighbor in grid"],
        "data_structures": ["Queue", "Grid", "Graph"],
        "requirements": ["Graph/Grid representation with adjacency access"],
        "input_characteristics": ["Graph or 2D matrix grid"],
        "constraints": ["Requires O(V) memory space for queue"],
        "best_use_cases": ["Finding shortest path in unweighted maze/grid", "Level-order traversal search"],
        "time_complexity": "O(V + E)",
        "space_complexity": "O(V)",
        "advantages": ["Guarantees shortest path in unweighted graphs"],
        "limitations": ["High memory consumption for wide graphs"],
        "alternatives": ["DFS Search", "A* Search"],
        "python_template": "from collections import deque\ndef bfs_search(grid, start, target):\n    queue = deque([start])\n    visited = set([start])\n    while queue:\n        curr = queue.popleft()\n        if curr == target: return True\n        for r, c in [(curr[0]+1, curr[1]), (curr[0]-1, curr[1]), (curr[0], curr[1]+1), (curr[0], curr[1]-1)]:\n            if 0 <= r < len(grid) and 0 <= c < len(grid[0]) and (r, c) not in visited:\n                visited.add((r, c))\n                queue.append((r, c))\n    return False"
    },
    {
        "id": "dfs_grid_search",
        "name": "DFS Search (Grid / Tree / Graph)",
        "category": "Searching",
        "description": "Explores as far as possible along each branch before backtracking using a stack or recursion.",
        "problem_patterns": ["deep search", "path existence", "maze traversal", "connected components search"],
        "data_structures": ["Stack", "Recursion", "Grid", "Graph"],
        "requirements": ["Graph or grid connectivity"],
        "input_characteristics": ["Tree, Graph, or 2D Grid"],
        "constraints": ["Recursion depth limits"],
        "best_use_cases": ["Checking path existence", "Topological sorting", "Solving maze puzzles"],
        "time_complexity": "O(V + E)",
        "space_complexity": "O(V)",
        "advantages": ["Memory efficient for deep narrow structures"],
        "limitations": ["Does not guarantee shortest path"],
        "alternatives": ["BFS Search", "Backtracking"],
        "python_template": "def dfs_search(grid, r, c, visited, target):\n    if (r, c) == target: return True\n    visited.add((r, c))\n    for dr, dc in [(1,0), (-1,0), (0,1), (0,-1)]:\n        nr, nc = r + dr, c + dc\n        if 0 <= nr < len(grid) and 0 <= nc < len(grid[0]) and (nr, nc) not in visited:\n            if dfs_search(grid, nr, nc, visited, target): return True\n    return False"
    },
    {
        "id": "two_pointer_search",
        "name": "Two Pointer Search",
        "category": "Searching",
        "description": "Algorithm pattern using two pointers moving toward each other or in parallel to search for pairs or subarrays matching conditions.",
        "problem_patterns": ["two sum sorted array", "pair sum target", "container with most water", "remove duplicates in place"],
        "data_structures": ["Array", "String"],
        "requirements": ["Sorted array or specific directional property"],
        "input_characteristics": ["Contiguous sequential data"],
        "constraints": ["Requires monotonic sequence behavior"],
        "best_use_cases": ["Finding pairs in sorted array summing to target", "Palindrome checks"],
        "time_complexity": "O(n)",
        "space_complexity": "O(1)",
        "advantages": ["Linear time O(n) with O(1) extra space"],
        "limitations": ["Requires input to be sorted for pair sum searching"],
        "alternatives": ["Hash Table Lookup", "Binary Search"],
        "python_template": "def two_pointer_sum(arr, target):\n    left, right = 0, len(arr) - 1\n    while left < right:\n        curr_sum = arr[left] + arr[right]\n        if curr_sum == target: return (left, right)\n        elif curr_sum < target: left += 1\n        else: right -= 1\n    return None"
    },
    {
        "id": "sliding_window_search",
        "name": "Sliding Window Search",
        "category": "Searching",
        "description": "Technique to maintain a dynamic range/subsegment over an array to search for optimal subsegment satisfying criteria.",
        "problem_patterns": ["max subarray sum of length k", "longest substring without repeating characters", "minimum window substring"],
        "data_structures": ["Array", "String", "Hash Map"],
        "requirements": ["Contiguous subarray/substring search requirements"],
        "input_characteristics": ["Sequential array or string"],
        "constraints": ["Window state must be incrementally updateable"],
        "best_use_cases": ["Finding max/min subarray meeting target condition", "Substring search"],
        "time_complexity": "O(n)",
        "space_complexity": "O(k) or O(1)",
        "advantages": ["Converts O(n^2) nested loops into linear O(n) single pass"],
        "limitations": ["Only applies to contiguous sequence problems"],
        "alternatives": ["Two Pointer Search", "Hash Table Lookup"],
        "python_template": "def sliding_window_max_sum(arr, k):\n    if len(arr) < k: return 0\n    window_sum = sum(arr[:k])\n    max_sum = window_sum\n    for i in range(len(arr) - k):\n        window_sum = window_sum - arr[i] + arr[i+k]\n        max_sum = max(max_sum, window_sum)\n    return max_sum"
    }
])

# ==================== 2. SORTING ====================
kb.extend([
    {
        "id": "bubble_sort",
        "name": "Bubble Sort",
        "category": "Sorting",
        "description": "Simple comparison sort that repeatedly steps through the list, compares adjacent elements and swaps them if in wrong order.",
        "problem_patterns": ["simple sorting", "adjacent element swaps", "educational sort"],
        "data_structures": ["Array"],
        "requirements": ["Comparable elements"],
        "input_characteristics": ["Small list or nearly sorted list"],
        "constraints": ["Quadratic time complexity O(n^2)"],
        "best_use_cases": ["Educational purposes", "Tiny arrays", "Detecting if array is already sorted"],
        "time_complexity": "O(n^2) worst/avg, O(n) best",
        "space_complexity": "O(1)",
        "advantages": ["In-place", "Stable", "Simple"],
        "limitations": ["Very slow for large arrays"],
        "alternatives": ["Insertion Sort", "Quick Sort"],
        "python_template": "def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        swapped = False\n        for j in range(0, n-i-1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n                swapped = True\n        if not swapped: break\n    return arr"
    },
    {
        "id": "selection_sort",
        "name": "Selection Sort",
        "category": "Sorting",
        "description": "In-place comparison sort that divides array into sorted and unsorted parts, repeatedly selecting the minimum from unsorted part.",
        "problem_patterns": ["minimize memory writes", "select minimum element repeatedly"],
        "data_structures": ["Array"],
        "requirements": ["Comparable items"],
        "input_characteristics": ["Small array size"],
        "constraints": ["Always O(n^2) comparisons regardless of input"],
        "best_use_cases": ["Small datasets where memory writing is expensive"],
        "time_complexity": "O(n^2)",
        "space_complexity": "O(1)",
        "advantages": ["Makes minimum number of memory writes O(n)", "In-place"],
        "limitations": ["Unstable sort", "Slow O(n^2)"],
        "alternatives": ["Insertion Sort", "Heap Sort"],
        "python_template": "def selection_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        min_idx = i\n        for j in range(i+1, n):\n            if arr[j] < arr[min_idx]: min_idx = j\n        arr[i], arr[min_idx] = arr[min_idx], arr[i]\n    return arr"
    },
    {
        "id": "insertion_sort",
        "name": "Insertion Sort",
        "category": "Sorting",
        "description": "Simple sorting algorithm that builds the final sorted array one item at a time, highly efficient for small or nearly sorted data.",
        "problem_patterns": ["nearly sorted array sort", "online stream sorting", "small subarray sort"],
        "data_structures": ["Array", "Linked List"],
        "requirements": ["Comparable items"],
        "input_characteristics": ["Small dataset or almost sorted data"],
        "constraints": ["O(n^2) for reverse ordered inputs"],
        "best_use_cases": ["Sorting small lists (n < 25)", "Online sorting of incoming items"],
        "time_complexity": "O(n^2) worst, O(n) best",
        "space_complexity": "O(1)",
        "advantages": ["Adaptive (O(n) on nearly sorted data)", "Stable", "In-place"],
        "limitations": ["High comparison cost on large unsorted arrays"],
        "alternatives": ["TimSort", "Merge Sort"],
        "python_template": "def insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j + 1] = key\n    return arr"
    },
    {
        "id": "merge_sort",
        "name": "Merge Sort",
        "category": "Sorting",
        "description": "Divide-and-conquer algorithm that recursively splits array into halves, sorts them, and merges sorted halves.",
        "problem_patterns": ["guaranteed O(n log n) sort", "external sorting", "linked list sorting", "stable sorting"],
        "data_structures": ["Array", "Linked List"],
        "requirements": ["Requires O(n) auxiliary space for arrays"],
        "input_characteristics": ["General large datasets"],
        "constraints": ["Auxiliary space O(n)"],
        "best_use_cases": ["Guaranteed O(n log n) sorting", "Sorting linked lists", "External sorting of big files"],
        "time_complexity": "O(n log n)",
        "space_complexity": "O(n)",
        "advantages": ["Stable sort", "Guaranteed O(n log n) performance", "Parallelizable"],
        "limitations": ["Requires extra O(n) space"],
        "alternatives": ["Quick Sort", "TimSort"],
        "python_template": "def merge_sort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]: result.append(left[i]); i += 1\n        else: result.append(right[j]); j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result"
    },
    {
        "id": "quick_sort",
        "name": "Quick Sort",
        "category": "Sorting",
        "description": "In-place divide-and-conquer sort selecting a pivot element and partitioning array into smaller and larger sub-arrays.",
        "problem_patterns": ["fast general sort", "in place partitioning", "cache friendly sorting"],
        "data_structures": ["Array"],
        "requirements": ["Random access memory array"],
        "input_characteristics": ["General unsorted array"],
        "constraints": ["Worst-case O(n^2) if pivot selection is poor"],
        "best_use_cases": ["Fast in-place general purpose sorting"],
        "time_complexity": "O(n log n) average, O(n^2) worst case",
        "space_complexity": "O(log n) stack space",
        "advantages": ["Fast in practice", "In-place", "Excellent cache locality"],
        "limitations": ["Unstable sort", "Worst-case quadratic time"],
        "alternatives": ["Merge Sort", "Heap Sort", "TimSort"],
        "python_template": "def quick_sort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + middle + quick_sort(right)"
    },
    {
        "id": "heap_sort",
        "name": "Heap Sort",
        "category": "Sorting",
        "description": "Comparison-based sorting technique based on Binary Heap data structure, finding maximum and placing it at the end.",
        "problem_patterns": ["in place O(n log n) sort", "priority queue sort", "top k elements sort"],
        "data_structures": ["Binary Heap", "Array"],
        "requirements": ["Comparable array elements"],
        "input_characteristics": ["General numerical or comparable arrays"],
        "constraints": ["Poor cache locality due to heap jumps"],
        "best_use_cases": ["Systems requiring guaranteed O(n log n) with O(1) auxiliary space"],
        "time_complexity": "O(n log n)",
        "space_complexity": "O(1)",
        "advantages": ["Guaranteed O(n log n)", "In-place O(1) extra space"],
        "limitations": ["Unstable sort", "Slower than QuickSort in practice"],
        "alternatives": ["Quick Sort", "Merge Sort"],
        "python_template": "import heapq\ndef heap_sort(arr):\n    heapq.heapify(arr)\n    return [heapq.heappop(arr) for _ in range(len(arr))]"
    },
    {
        "id": "counting_sort",
        "name": "Counting Sort",
        "category": "Sorting",
        "description": "Non-comparison integer sorting algorithm operating by counting number of objects having distinct key values.",
        "problem_patterns": ["integer array sort", "small key range sorting", "linear time non comparison sort"],
        "data_structures": ["Array", "Frequency Counter"],
        "requirements": ["Keys must be non-negative integers in small range K"],
        "input_characteristics": ["Integer values with known max range"],
        "constraints": ["Space consuming if range K is much larger than N"],
        "best_use_cases": ["Sorting discrete integers when range K is O(N)"],
        "time_complexity": "O(n + k)",
        "space_complexity": "O(n + k)",
        "advantages": ["Linear time O(n+k)", "Stable sort"],
        "limitations": ["Only works on integers or discrete keys", "High space if K is large"],
        "alternatives": ["Radix Sort", "Bucket Sort"],
        "python_template": "def counting_sort(arr):\n    if not arr: return arr\n    max_val = max(arr)\n    count = [0] * (max_val + 1)\n    for num in arr: count[num] += 1\n    sorted_arr = []\n    for val, freq in enumerate(count):\n        sorted_arr.extend([val] * freq)\n    return sorted_arr"
    },
    {
        "id": "radix_sort",
        "name": "Radix Sort",
        "category": "Sorting",
        "description": "Non-comparative integer sorting algorithm that sorts data with integer keys by grouping keys by individual digits.",
        "problem_patterns": ["digit by digit sorting", "large integer list sort", "fixed length string sort"],
        "data_structures": ["Array", "Buckets"],
        "requirements": ["Keys must be expressible in digit/character format"],
        "input_characteristics": ["Integers or fixed-length strings"],
        "constraints": ["Requires stable underlying digit sort"],
        "best_use_cases": ["Sorting large lists of integers or fixed-length strings in O(nk)"],
        "time_complexity": "O(d * (n + k))",
        "space_complexity": "O(n + k)",
        "advantages": ["Faster than O(n log n) comparison sorts for fixed digit length"],
        "limitations": ["Not general purpose, tied to key representations"],
        "alternatives": ["Counting Sort", "Bucket Sort"],
        "python_template": "def radix_sort(arr):\n    if not arr: return arr\n    max1 = max(arr)\n    exp = 1\n    output = [0] * len(arr)\n    while max1 // exp > 0:\n        count = [0] * 10\n        for i in range(len(arr)):\n            index = (arr[i] // exp) % 10\n            count[index] += 1\n        for i in range(1, 10): count[i] += count[i - 1]\n        i = len(arr) - 1\n        while i >= 0:\n            index = (arr[i] // exp) % 10\n            output[count[index] - 1] = arr[i]\n            count[index] -= 1\n            i -= 1\n        for i in range(len(arr)): arr[i] = output[i]\n        exp *= 10\n    return arr"
    },
    {
        "id": "bucket_sort",
        "name": "Bucket Sort",
        "category": "Sorting",
        "description": "Distribution sort that divides array into multiple buckets, then sorts individual buckets independently.",
        "problem_patterns": ["floating point uniform distribution sort", "bucket partition sort"],
        "data_structures": ["Array of Lists"],
        "requirements": ["Input should be uniformly distributed over a interval"],
        "input_characteristics": ["Floating point numbers in range [0, 1)"],
        "constraints": ["Worst-case O(n^2) if items cluster into one bucket"],
        "best_use_cases": ["Sorting floating point numbers uniformly distributed across a range"],
        "time_complexity": "O(n + k) average, O(n^2) worst case",
        "space_complexity": "O(n)",
        "advantages": ["Linear time O(n) average on uniform input"],
        "limitations": ["Performance degrades if data is heavily clustered"],
        "alternatives": ["Radix Sort", "Quick Sort"],
        "python_template": "def bucket_sort(arr):\n    if not arr: return arr\n    num_buckets = len(arr)\n    buckets = [[] for _ in range(num_buckets)]\n    for num in arr:\n        idx = int(num * num_buckets)\n        buckets[min(idx, num_buckets - 1)].append(num)\n    for i in range(num_buckets): buckets[i].sort()\n    res = []\n    for b in buckets: res.extend(b)\n    return res"
    },
    {
        "id": "shell_sort",
        "name": "Shell Sort",
        "category": "Sorting",
        "description": "In-place comparison sort generalization of insertion sort that allows exchanges of items that are far apart.",
        "problem_patterns": ["gap insertion sort", "diminishing increment sort"],
        "data_structures": ["Array"],
        "requirements": ["Comparable items"],
        "input_characteristics": ["Medium size arrays"],
        "constraints": ["Complexity depends heavily on gap sequence selection"],
        "best_use_cases": ["Embedded systems where code size must be minimal and memory limited"],
        "time_complexity": "O(n^(4/3)) to O(n^2)",
        "space_complexity": "O(1)",
        "advantages": ["In-place O(1) space", "Faster than insertion sort for medium arrays"],
        "limitations": ["Unstable sort", "Sub-optimal for huge arrays"],
        "alternatives": ["Quick Sort", "Insertion Sort"],
        "python_template": "def shell_sort(arr):\n    n = len(arr)\n    gap = n // 2\n    while gap > 0:\n        for i in range(gap, n):\n            temp = arr[i]\n            j = i\n            while j >= gap and arr[j - gap] > temp:\n                arr[j] = arr[j - gap]\n                j -= gap\n            arr[j] = temp\n        gap //= 2\n    return arr"
    },
    {
        "id": "timsort",
        "name": "TimSort",
        "category": "Sorting",
        "description": "Hybrid stable sorting algorithm derived from merge sort and insertion sort, standard default sort in Python and Java.",
        "problem_patterns": ["default language sort", "real world mixed data sort", "stable hybrid sort"],
        "data_structures": ["Array"],
        "requirements": ["Comparable items"],
        "input_characteristics": ["Real world data with existing run segments"],
        "constraints": ["Auxiliary space O(n)"],
        "best_use_cases": ["General purpose default sorting for real-world heterogeneous datasets"],
        "time_complexity": "O(n log n) worst, O(n) best",
        "space_complexity": "O(n)",
        "advantages": ["Extremely fast on real-world data with natural runs", "Stable", "Adaptive"],
        "limitations": ["Requires auxiliary memory O(n)"],
        "alternatives": ["Merge Sort", "Quick Sort"],
        "python_template": "def timsort(arr):\n    return sorted(arr)"
    }
])

print("Category Sorting completed.")
